# Generated by Django 4.2.9 on 2024-01-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('HR', 'Human resources'), ('F', 'Financial'), ('M_P', 'Manufacturing and production'), ('S_M', 'Sales and marketing'), ('IT', 'Technology')], max_length=5)),
                ('joining_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('department', models.CharField(choices=[('HR', 'Human resources'), ('F', 'Financial'), ('M_P', 'Manufacturing and production'), ('S_M', 'Sales and marketing'), ('IT', 'Technology')], max_length=5)),
                ('attendence', models.CharField(choices=[('A', 'ABSENT'), ('P', 'PRESENT')], max_length=2)),
                ('time_in', models.TimeField(default='00:00:00')),
                ('time_out', models.TimeField(default='00:00:00')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsapp.employee')),
            ],
        ),
    ]
